### ISSUE TITLE
Pinned google drive, gitlab, jira

### ISSUE THREAD

**Issue by JesseRiemens** [abrizuela/pinned_telegram#6]
Hi! 
You've got some cool extensions!

I have a request: could you make pinned google drive, gitlab, and jira extensions? Or perhaps a pinned_custom one? (That could create all favorite pinned tabs)
No pressure!

Thanks, 
Jesse

**Comment by abrizuela** [comment]
Hello Jesse!
Thanks for using my addons and for taking the time to writing me.
I'm finishing pinned_any_web (aka pinned_custom one). I'll let you know when is published (if we're lucky, today 😁).

The other ones you ask for, are all good ideas, I'll take them in mind.

Thank you!

**Comment by abrizuela** [comment]
Published!: https://addons.mozilla.org/es/firefox/addon/pinned-any-web/
